# Commands to start on workspace startup
tasks:
  - command: |
      docker compose up -d
      docker exec -i broker kafka-console-producer --broker-list broker:9092 --topic orders < orders.jsonl
      docker exec -i broker kafka-console-producer --broker-list broker:9092 --topic shipments < shipments.jsonl
      docker exec -it hazelcast hz-cli sql
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview