# Commands to start on workspace startup
tasks:
  - name: Clusters
    command: >
      docker compose up -d &&
      gp sync-done compose
  - name: Orders
    init: gp sync-await compose
    command: >
      docker exec -i broker kafka-console-producer --broker-list broker:9092 --topic orders < orders.jsonl &&
      gp sync-done orders
  - name: Shipments
    init: gp sync-await compose
    command: docker exec -i broker kafka-console-producer --broker-list broker:9092 --topic shipments < shipments.jsonl
  - name: SQL
    before: |
      clear
      echo "The clusters are being created in the background. \n"
      Check the Clusters tab on the right to see the progress. \n
      When all the processes have finished, this terminal will open a SQL shell."
    init: gp sync-await orders
    command: docker exec -it hazelcast hz-cli sql
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview